name: flutter_common_resources
description: "A package that contains common resources for Flutter projects."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Internationalization
  intl: ^0.19.0

  # Models
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3

  # Logger
  log_manager:
    git:
      url: https://github.com/bahricanyesil/flutter-advanced-template-v2.git
      path: packages/log_manager
      ref: 20a866728e902f4e8b5a69a207ce787e6daa5098

  # Theme
  theme_manager:
    git:
      url: https://github.com/bahricanyesil/flutter-advanced-template-v2.git
      path: packages/theme_manager

  # Language
  language_manager:
    git:
      url: https://github.com/bahricanyesil/flutter-advanced-template-v2.git
      path: packages/language_manager

  # Splash
  flutter_native_splash: ^2.4.1

  # Images
  flutter_svg: ^2.0.10+1

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6

  # Loading
  flutter_spinkit: ^5.2.1

  # Navigation
  go_router: ^14.3.0

dev_dependencies:
  # Lint
  lint_rules:
    git:
      url: https://github.com/bahricanyesil/flutter-advanced-template-v2.git
      path: packages/lint_rules